### ISSUE TITLE
Calculating power in Rid-rihazcek 

### ISSUE THREAD

**Issue by MOH-Shafizadegan** [erawls-neuro/NeuroFreq_public#1]
Hi,

First, I would like to thank you for your work on this project.

I have a question about the way you have calculated the power in the Rid-rihazcek code (transforms/nf_ridrihaczek.m)
In line `116` of `transforms/nf_ridrihaczek.m`, the `real` function has been used to calculate the power.
```
    ridPowDat(eloc,:,:,trl) = real( RID_Rih(1:numel(fout),:) );
```
I wonder if the `abs` function must be used in the following way instead:
```
    ridPowDat(eloc,:,:,trl) = abs( RID_Rih(1:numel(fout),:)) .^ 2;
```

Thanks and regards

**Comment by erawls-neuro** [comment]
As with the other quadratic methods we do not return the squared absolute-value. This is in contrast to the linear methods, where we do return the squared-absolute-value.

The quadratic time-frequency distributions are formulated to satisfy time and frequency marginals, and this property is lost if the distribution is absolute-valued and squared. 

Note the real part of the Rihaczek distribution is itself a distribution (the Margenau-Hill distribution [1]) which also has correct time and frequency marginals - so we take the real part to avoid returning complex-valued magnitudes.

If a TF distribution with no negative terms is desired, use the 'makePos' option instead, to set all negative values equal to the smallest positive value.

Hope this helps. E

[1] H. Margenau, R. Hill. “Correlation between Measurements in Quantum Theory”, Prog. Theor. Phys. Vol. 26, pp. 722-738, 1961.
